language: generic
dist: trusty
group: deprecated-2017Q3

before_install:
    sudo apt-get install tidy dos2unix android-tools-fsutils

script:
    ./script/download.sh && ./script/push.sh

after_sucess:

